### ISSUE TITLE
Internet backup

### ISSUE THREAD

**Issue by lgLindstrom** [dparoli/hrsync#2]
Hi

I've tried to modify your script to perform backup over internet using ssh. No sucess,, so I guess that I dont fully understand your script.

Can you give me a hint how to do it??

Regards
lg

**Comment by dparoli** [comment]
I have modified the script, it now accepts a third parameter: the remote host.
The script can now be called in this way:
```sh
./hrsync /home/user/Documents /root/Documents root@example.com
```
Please do your tests on crap files before doing real things, the changes seems to work but are quite untested.

**Comment by lgLindstrom** [comment]
Hi and thanks.

As far as I can tell..(I have done some testing ) and it works well.

Only "problem" I can find is international characters in text files. This not is a concern of your script .

/regards
/lg

**Comment by dparoli** [comment]
@lgLindstrom Thanks for your contribution to the project. 
I close this issue and marked as resolved, in case you have some bug report or feature request feel fre to open a specific issue.
